#' Combine evaluation metrics across multiple models
#'
#' Combines model performance metrics from multiple externally evaluated
#' models into a single data frame and identifies the top-performing models
#' according to a selected metric and ranking criterion.
#'
#' @param models A list of model evaluation results. Each element must be a
#' named list containing:
#' \itemize{
#'   \item \code{model_name}: Character string identifying the model.
#'   \item \code{metrics_list}: Output object containing
#'   \code{metrics_means}, typically generated by [metrics_occ()].
#' }
#'
#' 
#' @param metric Character string specifying the metric used for ranking
#' models (e.g., \code{"MAIPE"}, \code{"IF20"}, \code{"IF30"},
#' \code{"rBIAS"}).
#' 
#' 
#' @param top_n Integer. Number of top-performing models to retain.
#' 
#' @param occ_eval Numeric or character value specifying the evaluation
#' occasion (\code{OCC}) used for ranking. Default is \code{2}.
#' 
#' @param rank_criteria Character string specifying the ranking rule:
#' \itemize{
#'   \item \code{"min"}: selects models with the lowest metric values
#'   (e.g., \code{MAIPE}).
#'   \item \code{"max"}: selects models with the highest metric values
#'   (e.g., \code{IF30}).
#'   \item \code{"abs"}: selects models with the smallest absolute metric
#'   values (e.g., \code{rBIAS}).
#' }
#' 
#' @details
#' All models must have been evaluated using the same external evaluation
#' strategy (\code{eval_type}), otherwise the function stops with an error.
#'
#' Top-performing models are identified internally according to the
#' selected metric and ranking criterion.
#'
#' @return A named list containing:
#' \describe{
#'   \item{cmetrics}{Combined data frame containing metrics for all input
#'   models, with an additional \code{Model} column.}
#'
#'   \item{topmodelspd}{Data frame containing the top-performing models
#'   according to the selected ranking criteria.}
#' }
#'
#' @seealso [metrics_occ()]
#'
#' 
#' @examples
#' \dontrun{
#' set.seed(123)
#' generate_fake_metrics <- function(n_occasions = 3) {
#' data.frame(
#' OCC = rep(1:n_occasions),  # Simula varias ocasiones
#' rBIAS = rnorm(n_occasions, mean = 0, sd = 10),
#' rBIAS_lower = rnorm(n_occasions, mean = -5, sd = 5),
#' rBIAS_upper = rnorm(n_occasions, mean = 5, sd = 5),
#' MAIPE = runif(n_occasions, min = 10, max = 50),
#' IF20 = runif(n_occasions, min = 20, max = 80),
#' IF30 = runif(n_occasions, min = 30, max = 90)
#' )
#' }
#' # Save Results of metrics
#' simulation1 <- list(metrics_means = generate_fake_metrics())
#' simulation2 <- list(metrics_means = generate_fake_metrics())
#' # List of models
#' models_list <- list(
#' list(model_name = "Test_Model1", metrics_list = simulation1),
#' list(model_name = "Test_Model2", metrics_list = simulation2)
#' )
#'combined_results <- combine_metrics(models_list)
#'print(combined_results)
#'
#' }
#' @export

combine_metrics <-function(models,
                           metric ='MAIPE',
                           top_n = 2,
                           occ_eval = 2,
                           rank_criteria = 'min') {
  combined_data <- NULL

  # Extract all the evaluation type in the models to be compared
  eval_types <- sapply(models, function(model) model$metrics_list$eval_type)

  # Check que todos sean iguales
  if (length(unique(eval_types)) > 1) {
    stop("Error: Models must have the same 'eval_type' to be combined.")
  }


  for (entry in models) {
    model_name <- entry$model_name
    metrics_list <- entry$metrics_list

    # add model name
    metrics_data <- metrics_list$metrics_means |> mutate(Model = model_name)

    # combined with data
    combined_data <- if (!is.null(combined_data)) {
      bind_rows(combined_data, metrics_data)
    } else {
      metrics_data
    }
  }



  top_models <- select_best_models(data          = combined_data,
                                   metric        = metric,
                                   top_n         = top_n,
                                   occ_eval      = occ_eval,
                                   rank_criteria = rank_criteria)

  return(list(cmetrics = combined_data, topmodelspd = top_models))
}
