#' Plot individual model fit
#'
#' Visualizes observed versus predicted concentrations for a selected individual
#' across pharmacokinetic evaluation occasions.
#'
#' @param simulations Output generated by [run_pk_simulations()].
#' @param id Numeric or character subject ID to visualize.
#' @param occ Optional numeric occasion to filter.
#' @param relative_time Logical. If TRUE (default), time is displayed relative
#'   to the first observation in each occasion.
#' @param show_error Logical. If TRUE (default), percentage prediction error
#'   labels are displayed.
#' @param error_threshold Numeric. Minimum absolute IPE (%) required to display
#'   error labels. Default = 5.
#' @param log_scale Logical. If TRUE, use log10 concentration scale.
#' @param target_low Optional numeric lower therapeutic target.
#' @param target_high Optional numeric upper therapeutic target.
#' @param nrow Optional number of rows for facet layout.
#' @param ncol Optional number of columns for facet layout.
#'
#' @return ggplot object
#' @export

plot_individual_fit <- function(simulations,
                                id,
                                occ = NULL,
                                relative_time = TRUE,
                                show_error = TRUE,
                                error_threshold = 5,
                                log_scale = FALSE,
                                target_low = NULL,
                                target_high = NULL,
                                nrow = NULL,
                                ncol = NULL) {

  df <- extract_predictions(simulations) %>%
    dplyr::filter(ID == id)

  if (!is.null(occ)) {
    df <- df %>%
      dplyr::filter(OCC == occ)
  }

  if (nrow(df) == 0) {
    stop("No prediction data found for selected ID/OCC.")
  }

  df <- df %>%
    dplyr::mutate(
      IPE = ((Prediction - DV) / DV) * 100
    )

  if (relative_time) {
    df <- df %>%
      dplyr::group_by(OCC) %>%
      dplyr::mutate(
        Plot_Time = TIME - min(TIME, na.rm = TRUE)
      ) %>%
      dplyr::ungroup()
  } else {
    df <- df %>%
      dplyr::mutate(
        Plot_Time = TIME
      )
  }

  facet_labels <- df %>%
    dplyr::group_by(OCC) %>%
    dplyr::summarise(
      n = dplyr::n(),
      .groups = "drop"
    ) %>%
    dplyr::mutate(
      OCC_Label = paste0("OCC ", OCC, " (n=", n, ")")
    )

  df <- dplyr::left_join(df, facet_labels, by = "OCC")

  p <- ggplot2::ggplot(df, ggplot2::aes(x = Plot_Time)) +

    ggplot2::geom_segment(
      ggplot2::aes(
        xend = Plot_Time,
        y = DV,
        yend = Prediction
      ),
      alpha = 0.6,
      linewidth = 0.7
    ) +

    ggplot2::geom_point(
      ggplot2::aes(
        y = DV,
        color = "Observed"
      ),
      size = 2
    ) +

    ggplot2::geom_point(
      ggplot2::aes(
        y = Prediction,
        color = "Predicted"
      ),
      size = 2
    ) +

    ggplot2::facet_wrap(
      ~ OCC_Label,
      scales = "free_x",
      nrow = nrow,
      ncol = ncol
    ) +

    ggplot2::scale_color_manual(
      values = c(
        "Observed" = "black",
        "Predicted" = "#E76F51"
      )
    ) +

    ggplot2::labs(
      title = paste("Individual fit — ID:", id),
      x = ifelse(relative_time, "Relative Time", "Time"),
      y = "Concentration",
      color = NULL
    ) +
    ggplot2::theme_bw()

  if (show_error) {

    df_labels <- df %>%
      dplyr::filter(abs(IPE) >= error_threshold)

    p <- p +
      ggplot2::geom_text(
        data = df_labels,
        ggplot2::aes(
          x = Plot_Time,
          y = Prediction,
          label = paste0(round(IPE, 1), "%")
        ),
        vjust = -0.8,
        size = 3,
        check_overlap = TRUE
      )
  }

  if (!is.null(target_low)) {
    p <- p +
      ggplot2::geom_hline(
        yintercept = target_low,
        linetype = 2
      )
  }

  if (!is.null(target_high)) {
    p <- p +
      ggplot2::geom_hline(
        yintercept = target_high,
        linetype = 2
      )
  }

  if (log_scale) {
    p <- p + ggplot2::scale_y_log10()
  }

  if (relative_time) {
    p <- p +
      ggplot2::coord_cartesian(xlim = c(0, NA))
  }

  return(p)
}


