#' Run Individual Simulations
#'
#' Simulates concentration-time profiles for external model evaluation using
#' either population predictions (a priori), individual posterior predictions
#' (Bayesian forecasting), or both, depending on the selected assessment strategy.
#'
#' #' @param individual_model A list object generated by [actualize_model()]
#'   containing posterior individual models used for Bayesian forecasting.
#'   Ignored when `assessment = "a_priori"`.
#'
#' @param tto_occ A list object generated from the `run_map_estimations` function. It contains treatment schedules for every ID in each occasion.
#'
#' #' @param tto_occ A list object generated by [run_MAP_estimations()]
#'   containing treatment schedules, evaluation metadata, and the population
#'   model used for simulations.
#'
#'
#' @param assessment Character string specifying the prediction strategy.
#'   Options are:
#'   \itemize{
#'     \item \code{"a_priori"}: Simulates concentrations using the population model
#'     without individual posterior information.
#'     \item \code{"Bayesian_forecasting"}: Simulates concentrations using
#'     individual posterior parameter estimates.
#'     \item \code{"Complete"}: Performs both a priori and Bayesian forecasting
#'     simulations.
#'   }
#'
#' @param verbose Logical. If TRUE, messages are printed during execution.
#'   If FALSE (default), errors are stored as warnings accessible with `warnings()`.
#'
#' @return A list containing:
#' \describe{
#'   \item{simulation_results}{A list of simulation outputs for each individual
#'   and occasion.}
#'   \item{ttoocc}{A list of treatment schedules organized by occasion.}
#'   \item{eval_type}{The evaluation strategy used (e.g. Progressive,
#'   Most_Recent_Progressive).}
#'   \item{events_tto}{A list containing treatment event datasets used for
#'   each simulation.}
#'   \item{assessment}{The selected simulation strategy:
#'   \code{"a_priori"}, \code{"Bayesian_forecasting"}, or \code{"Complete"}.}
#' }
#'
#'
#' @details #' This function performs pharmacokinetic simulations at the observation times
#' available in the input dataset for external model evaluation.
#' For each posterior estimation, it retrieves the corresponding treatment schedule and executes a simulation
#' over the specified time range. The results are stored for each individual within each occasion.
#'
#' #' Depending on the selected \code{assessment}, simulations are performed using:
#' \itemize{
#'   \item the population model for a priori predictions
#'   \item posterior individual models for Bayesian forecasting
#'   \item both approaches when complete evaluation is requested
#' }
#'
#' For a priori predictions, the population model is used together with the
#' treatment history of each individual.
#'
#' For Bayesian forecasting, simulations are based on posterior models generated
#' from MAP estimation and updated according to the selected evaluation strategy
#'
#' @examples
#' \dontrun{
#' # Assuming `individual_model` is created with actualize_model
#' # and `tto_occ` is created with run_map_estimations:
#'
#' results <- run_ind_simulations(individual_model, tto_occ)
#'
#' # Access simulation results
#' sim_results <- results$simulation_results
#'
#' # Access treatment by occasion
#' treatments <- results$ttoocc
#'
#' # Access treatment events
#' events <- results$events_tto
#'}
#' @seealso \code{\link{actualize_model}}, \code{\link{run_MAP_estimations}}
#'
#' @export

run_ind_simulations <- function(individual_model,
                                tto_occ,
                                assessment = c("a_priori","Bayesian_forecasting","Complete"),
                                verbose= FALSE) {

  assessment <- match.arg(assessment)
  evaluation_type <-tto_occ$eval_type
  # Listas vacías para acumular resultados
  simulation_results <- list()
  event.tto <- list()
  treatment.occ.list <- list()


  ## 1. Simulaciones a priori
  if (assessment %in% c("a_priori", "Complete")) {

    population_model <- tto_occ$pop_model

    if (is.null(population_model)) {
      stop("Population model not found in tto_occ.")
    }

    tto_apriori <- tto_occ$apriori_treatments

    treatment_list <- tto_apriori[["tto_1"]]
    treatment.occ.list[["OCC1"]] <- treatment_list
    events_apriori <- tto_apriori[["apriori_occ_1"]]

    event.tto.byocc <- list()

    for (id_name in names(events_apriori)) {
      id_number <- sub(".*ID", "", id_name)

      tryCatch({
        set.seed(12345)
        treatment <- tto_apriori[["apriori_occ_1"]][[paste0("ev.tto.occ1_ID", id_number)]]
        start <- min(treatment$TIME)
        end <- max(treatment$TIME)
        sim_results <- individual_sim(population_model, treatment, start, end)
        sim_results@data <- subset(sim_results@data, OCC == 1)

        simulation_results[[paste0("OCC_1_ID", id_number)]] <- sim_results
        event.tto.byocc[[paste0("ID_", id_number)]] <- treatment

      }, error = function(e) {
        if (verbose) {
        message(paste0("Could not simulate ID_", id_number, " in OCC1 (a_priori): ", e$message))
        } else {
          warning(paste0("Could not simulate ID_", id_number, " in OCC1 (a_priori): ", e$message),
                  call. = FALSE, immediate. = FALSE)
        }
      })
    }

    event.tto[["OCC_1"]] <- event.tto.byocc
  }

  ## 2. simulations
  if (assessment %in% c("Bayesian_forecasting", "Complete")) {

    posterior_estimations <- individual_model$ind_model
    tto_by_occ <- tto_occ$treatments_by_occ

    for (occasion_name in names(posterior_estimations)) {
      occ_posterior <- posterior_estimations[[occasion_name]]
      occ_number <- sub(".*_", "", occasion_name)
      tto.occ.names <- paste0("OCC", occ_number)

      event.tto.byocc <- list()
      treatment.occ.list[[tto.occ.names]] <- tto_by_occ[[paste0("tto_", occ_number)]]

      for (id_identifyer in names(occ_posterior)) {
        id_posterior <- occ_posterior[[id_identifyer]]
        id_number <- sub("ID_", "", id_identifyer)

        tryCatch({
          treatment <- tto_by_occ[[paste0("tto_occ_", occ_number)]][[paste0("ev.tto.occ", occ_number, "_ID", id_number)]]
          start <- min(treatment$TIME)
          end <- max(treatment$TIME)
          sim_results <- individual_sim(id_posterior, treatment, start, end)
          sim_results@data <- subset(sim_results@data, OCC == occ_number)

          simulation_results[[paste0("OCC_", occ_number, "_ID", id_number)]] <- sim_results
          event.tto.byocc[[paste0("ID_", id_number)]] <- treatment

        }, error = function(e) {
          if(verbose) {
            message(paste0("Could not process OCC_", occ_number, " ID_", id_number, ": ", e$message))
          } else {
            warning(paste0("Could not process OCC_", occ_number, " ID_", id_number, ": ", e$message),
                           call. = FALSE, immediate. = FALSE)
            }
        })
      }

      event.tto[[paste0("OCC_", occ_number)]] <- event.tto.byocc
    }
  }


  ## Return unified output
  out <-list(
    simulation_results = simulation_results,
    ttoocc = treatment.occ.list,
    eval_type=evaluation_type,
    events_tto = event.tto,
    assessment = assessment
  )

  class(out) <- "mapbayr"
  return(out)

}






